### PR TITLE
feat: add integrated projects

### LINKED ISSUE #2: Add Other Half of Curriculum
Add Tom's section of the curriculum.

### PR DESCRIPTION
**Pull request by moT01**
First project added
TODO: Add second project

I made a few small changes to the Dockerfile - it wasn't working for me. See https://github.com/freeCodeCamp/rdb-alpha/issues/11

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #2

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
I am going to cause you many conflicts, and will resolve those myself, but I want to merge my PR first.

> I made a few small changes to the Dockerfile

This is odd, because `22.04` is officially released now, and I am using it everywhere I can.

**Comment by moT01** [comment]
I glanced at your PR - I really didn't see much that might conflict. Looks like they're resolved. Perhaps you meant stuff is just going to break. I can take a look if needed.

I'll give it one more test - but yea, 22.04 wasn't working for me. Maybe my mac? older version of docker? possibly.

**Comment by ShaunSHamilton** [comment]
I am trying to figure out why `rm -r !(...)` no longer works. Maybe a Gitpod thing?

**Comment by ShaunSHamilton** [comment]
Tom, this should work now. I definitely should clean up the pathing - too many joins and relative paths.

I think I am just going to merge this as is, and keep working from there.

**Review by ShaunSHamilton — APPROVED** [review]
🤷‍♂️

**Pull request merged**
